runtime: python
env: flex
entrypoint: gunicorn -b :$PORT app:app

instance_class: F2
automatic_scaling:
  target_cpu_utilization: 0.65
  min_instances: 1
  max_instances: 5

env_variables:
  MONGO_URI: 'your_mongodb_connection_string'
