steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/realfag-net-docker/realfag-net:$COMMIT_SHA', '.']
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/realfag-net-docker/realfag-net:$COMMIT_SHA']
images:
  - 'gcr.io/realfag-net-docker/realfag-net:$COMMIT_SHA'
substitutions:
  _SERVICE_NAME: 'realfag-net-docker'
steps:
  - name: 'gcr.io/cloud-builders/gcloud'
    entrypoint: 'bash'
    args:
      - '-c'
      - |
        gcloud run deploy realfag-net-docker \
          --image gcr.io/realfag-net-docker/realfag-net:$COMMIT_SHA \
          --platform managed \
          --region us-central1
